### ISSUE TITLE
Device group filter on more device fields

### ISSUE THREAD

**Issue by Qwiko** [SUNET/cnaas-nms#401]
**Is your feature request related to a problem? Please describe.**
It would be nice to have more advanced group filtering.

One example use-case is being able to filter what users see in interface tags depending on device model or platform. For example display poe-disable tag only if the switch is a poe enabled switch or display mlag port tag only if the switch supports mlag.

Also firmware update would become more clear when having multiple vendors in a single cnaas-nms instance and same roles. You could then have a group called ACCESS_IOS and ACCESS_EOS, although that is not as necessary right now.

**Describe the solution you'd like**
Add more device fields to group filtering with regex support on those fields where every field filter is considered with implicit AND logic.
Example:
```yaml
groups:
  - group:
      name: "ACCESS_EOS"
      device_role: "ACCESS"
      platform: "eos"
  - group:
      name: "ACCESS_EOS_POE"
      device_role: "ACCESS"
      device_model: "some_regex_here"
      platform: "eos"
```

I am willing to try to implement this with more attributes and keep it very simple so existing setups are not broken.

**Comment by Qwiko** [comment]
Adding additional field filtering like the above example is not very clear due to the name field is not a filter on the device name but the actual name of the group, the regex field is the filter on device names.

Maybe a redesign with backwards compability needs to be made.

Example redesign:
```yaml
groups:
  ACCESS_EOS:
    filter:
      device_role: "ACCESS"
      platform: "eos"
    priority: 90
  ACCESS_EOS_POE:
    filter:
      device_role: "ACCESS"
      device_model: "some_regex_here"
      platform: "eos"
    priority: 100
```
Or a more similar approach to the current setup.
```yaml
groups:
  - group:
      name: "ACCESS_EOS"
      filter:
        device_role: "ACCESS"
        platform: "eos"
      priority: 90
  - group:
      name: "ACCESS_EOS_POE"
      filter:
        device_role: "ACCESS"
        device_model: "some_regex_here"
        platform: "eos"
      priority: 100
```
Another possible design based on the current concept but removes the unnecessary nested group dict and places the group object directly in the groups array. Also uses a more clear key: device_filter.
```yaml
groups:
  - name: "ACCESS_EOS"
    device_filter:
      name: "some_regex_here"
      device_role: "ACCESS"
      platform: "eos"
    priority: 90
  - name: "ACCESS_EOS_POE"
    device_filter:
      device_role: "ACCESS"
      device_model: "some_regex_here"
      platform: "eos"
    priority: 100
```
This filter could be dynamic and be possible on every field that devices have and if something is added to devices it can be used to filter groups without changing the group filter logic.

The second approach initially seems easier to implement and the only breaking change is moving the regex field to be used in filter.name instead and could be added with a deprecation notice to the regex field.
However the third option is the most clean but requires a bigger change.

**Comment by indy-independence** [comment]
Maybe we can make some breaking changes and then provide a tiny migration script to convert old syntax to the new one?
I think it would also be nice to be able to just specify a list of device hostnames instead of a regexp for users not familiar with regexp, not sure it fits with implicit AND logic but maybe it can just error out if user provided both regex and list of hostnames

**Comment by Qwiko** [comment]
Good idea, maybe having dictionary called device_filter or an array of devices.
```yaml
groups:
  - name: "ACCESS_EOS"
    device_filter:
      name: "some_regex_here"
      device_role: "ACCESS"
      platform: "eos"
    priority: 90
  - name: "ACCESS_EOS_POE"
    devices:
      - eosaccess-1
      - eosaccess-2 
    priority: 100
```
And erroring when both are defined at the same time.

It should be possible using pydantic to have two different models at the same time using the Union-type and check with ifinstance if it is the old-style config and run to_new_model when used in get_groups. Then we have backwards-compability and only use one type of grouping logic. Some example-code:

```python
from typing import Annotated, Union
from typing_extensions import Self

from pydantic import BaseModel, model_validator

#old style
class f_group_old(BaseModel):
    group: Annotated[Optional[f_group_item], Field(deprecated='This syntax is deprecated and will be removed in a future version')] = None

    def to_new_model(self) -> 'f_group':
        device_filter = f_group_device_filter(name=self.regex)
        return f_group(name=self.name,device_filter=device_filter)

#new style
class f_group(BaseModel):
    name: str = group_name
    device_filter: Optional[f_group_device_filter] = None
    devices: Optional[List[str]] = None
    group_priority: int = group_priority_schema
    templates_branch: Optional[str] = None

    @model_validator(mode="after")
    def cannot_use_device_filter_with_devices(self: Self) -> Self:
        device_filter = self.device_filter
        devices = self.devices
        if device_filter and devices:
            raise ValueError("cannot use device_filter together with devices")

        return self

class f_groups(BaseModel):
    groups: Optional[List[Union[f_group_old, f_group]]] = None
```

This together with a migration-script should be a good way to do it and fully remove the old-syntax in a later version.
@indy-independence why is the nested group dict used, was there any design choice made that you would like to keep?
