### ISSUE TITLE
Integration-tests using containerlab

### ISSUE THREAD

**Issue by Qwiko** [SUNET/cnaas-nms#408]
**Is your feature request related to a problem? Please describe.**
I am starting an issue where we can discuss integration-tests using containerlab.

I found this setting: [suppress-startup-config](https://containerlab.dev/manual/nodes/#suppress-startup-config) in containerlab that sets a node in zerotouch that could be what we need to have integration-tests more accessible, just need to download a ceos image from Arista.

**Describe the solution you'd like**
I would like an in-tree full integration-test that does not depend on alot of external stuff. Or at least the resources should be open and easily accessible.

Containerlab also have a solution to connect other virtual-machines to the lab, example is a catalyst switch or a juniper device. Maybe dynamically run tests on different providers depending on if the user that run the tests actually have the correct images downloaded because some images can be behind a paywall.

**Describe alternatives you've considered**

**Additional context**
Example containerlab file
```yaml
name: cnaas-integration

mgmt:
  network: cnaas_mgmt # management network name
  ipv4-subnet: 10.100.2.0/24 # ipv4 range
  ipv4-gw: 10.100.2.2

topology:
  kinds:
    arista_ceos:
      image-pull-policy: Never
    arista_veos:
      image-pull-policy: Never
  nodes:
    eosdist1:
      kind: arista_ceos
      image: ceos:4.32.5.1M
      startup-config: eosdist1_startup_config.txt
      mgmt-ipv4: 10.100.2.11
    eosdist2:
      kind: arista_ceos
      image: ceos:4.32.5.1M
      startup-config: eosdist2_startup_config.txt
      mgmt-ipv4: 10.100.2.12
    eosaccess:
      kind: arista_veos
      image: vrnetlab/arista_veos:4.32.5.1M
      suppress-startup-config: true

  links:
    - endpoints: ["eosdist1:eth3", "eosdist2:eth3"]
    - endpoints: ["eosdist1:eth2", "eosaccess:eth2"]
    - endpoints: ["eosdist2:eth2", "eosaccess:eth3"]

    # Management network
    - endpoints: ["eosdist1:eth1", "mgmt-net:eosdist1-eth1"]
    - endpoints: ["eosdist2:eth1", "mgmt-net:eosdist2-eth1"]
```

cEOS used for dist nodes
vEOS with vrnetlab used for access-switch (to enable ztp functionality)
startup-config set from: https://wiki.sunet.se/display/CNaaS/CNaaS+NMS+Development+Environment and static routes added to the host node.

**Comment by Qwiko** [comment]
I managed to get this working by changing the veos container from vrnetlab to actually run ztp when booted
I had to tweak a couple of things and rearranged some tests to get everything working properly.
I was getting an error where I could not sync templates before settings had been synced first.
Also site_id = 1 is not automatically added when running integration_tests locally so I had to create that site manually for the tests to pass (test_add_device).

I will try to formulate all my findings here later.

**Comment by Qwiko** [comment]
# Containerlab integration tests

## cEOS and vEOS docker images

You need to have nested virtualization enabled for the VM or host you create this environment in.  
I created this in a VM in a vSphere environment.

### cEOS
I followed the guide here to import ceos images to my local docker environment.
https://containerlab.dev/manual/kinds/ceos/

### vEOS
For vEOS I followed the guide here: https://containerlab.dev/manual/kinds/vr-veos/ and here: https://github.com/hellt/vrnetlab/tree/master/veos

For the vEOS image I had to modify the start script so it starts in ZTP mode.

First modify the Makefile and swap out the docker-pre-build so it configures a zerotouch-config file with Disabled=False.
```Make
# File: vrnetlab/veos/Makefile
docker-pre-build:
	# checking if ZTP config contains a string (DISABLE=False) in the file /zerotouch-config
	# if it does, we don't need to write this file
	@echo Checking ZTP status
	ZTPOFF=$(shell docker run --rm -it -e LIBGUESTFS_DEBUG=0 -v $$(pwd):/work cmattoon/guestfish --ro -a $(IMAGE) -m /dev/sda2 cat /zerotouch-config 2> /dev/null || echo "false"); \
	echo "$@: ZTPOFF is $$ZTPOFF" && \
	if [ "$$ZTPOFF" != "DISABLE=False" ]; then \
	  echo "Enabling ZTP" && docker run --rm -it -e LIBGUESTFS_DEBUG=0 -v $$(pwd):/work cmattoon/guestfish -a $(IMAGE) -m /dev/sda2 write /zerotouch-config "DISABLE=False"; \
	fi
```

Then modify the docker/launch.py script to not do any initial config.
I just commented out the following lines in the function `bootstrap_spin` on line 71->76

```python3
# File: vrnetlab/veos/docker/launch.py
# Omitted lines ...
    def bootstrap_spin(self):
# Omitted lines ...
                # self.logger.debug("matched login prompt")
                # self.logger.debug("trying to log in with 'admin'")
                # self.wait_write("admin", wait=None)

                # run main config!
                # self.bootstrap_config()
# Omitted lines ..
```

You can then run `make` to create the image. Follow the README guide to place the vEOS.vmdk in the correct place.

#### serial access to vEOS
To get serial access to the vEOS image you can run `telnet 10.105.2.1 5000` to see ZTP progress. Then later when it have been initally configured you can access with ssh as well.


## containerlab config

```yaml
# File: cnaas-integration.clab.yml
name: cnaas-integration

mgmt:
  network: cnaas_mgmt # management network name
  ipv4-subnet: 10.100.2.0/24 # ipv4 range
  ipv4-gw: 10.100.2.2

topology:
  kinds:
    arista_ceos:
      image-pull-policy: Never
    arista_veos:
      image-pull-policy: Never
  nodes:
    eosdist1:
      kind: arista_ceos
      image: ceos:4.32.5.1M
      startup-config: eosdist1_startup_config.txt
      mgmt-ipv4: 10.100.2.11
    eosdist2:
      kind: arista_ceos
      image: ceos:4.32.5.1M
      startup-config: eosdist2_startup_config.txt
      mgmt-ipv4: 10.100.2.12
    eosaccess:
      kind: arista_veos
      image: vrnetlab/arista_veos:4.32.5.1M
      suppress-startup-config: true

  links:
    - endpoints: ["eosdist1:eth3", "eosdist2:eth3"]
    - endpoints: ["eosdist1:eth2", "eosaccess:eth2"]
    - endpoints: ["eosdist2:eth2", "eosaccess:eth3"]

    # Extra management interfaces connected to the clab management
    # https://containerlab.dev/manual/network/#additional-connections-to-management-network
    - endpoints: ["eosdist1:eth1", "mgmt-net:eosdist1-eth1"]
    - endpoints: ["eosdist2:eth1", "mgmt-net:eosdist2-eth1"]
```

### eosdist1_startup_config.txt
```txt
! File: eosdist1_startup_config.txt
hostname eosdist1
username admin privilege 15 role network-admin secret abc123abc123
vrf instance MGMT
interface Ethernet1
   no switchport
   vrf MGMT
   ip address 10.100.2.101/24
   no lldp transmit
   no lldp receive
interface Ethernet2
   description DOWNLINK
   switchport mode trunk
   channel-group 3 mode active
!
interface Port-Channel3
   description DOWNLINK
   switchport mode trunk
   port-channel lacp fallback individual
   port-channel lacp fallback timeout 3
!
interface Loopback1
   vrf MGMT
   ip address 10.100.3.101/32
!
interface Vlan1
   description ZTP DHCP
   vrf MGMT
   ip address 192.168.0.1/24
   ip helper-address 10.100.2.2
!
vlan 600
!
interface Vlan600
 vrf MGMT
 ip address virtual 10.0.6.1/24
 arp aging timeout 180
!
ip routing vrf MGMT
management api http-commands
   no shutdown
   !
   vrf MGMT
      no shutdown
```

### eosdist2_startup_config.txt
```txt
! File: eosdist2_startup_config.txt
hostname eosdist2
username admin privilege 15 role network-admin secret abc123abc123
vrf instance MGMT
interface Ethernet1
   no switchport
   vrf MGMT
   ip address 10.100.2.102/24
   no lldp transmit
   no lldp receive
!
interface Loopback1
   vrf MGMT
   ip address 10.100.3.102/32
!
ip routing vrf MGMT
management api http-commands
   no shutdown
   !
   vrf MGMT
      no shutdown
```

Then you can run the containerlab with
```bash
sudo containerlab deploy

# If you need to reconfigure the lab from the beginning
sudo containerlab deploy --reconfigure
```

On your host you need to configure static routes for NMS to reach your containerlab through the host-networking.  
When destroying your containerlab the static routes are removed. Only running deploy with --reconfigure the static routes are preserved.
```bash
sudo ip route add 10.0.6.0/24 via 10.100.2.101
sudo ip route add 192.168.0.0/24 via 10.100.2.101
sudo ip route add 10.100.3.101/32 via 10.100.2.101
sudo ip route add 10.100.3.102/32 via 10.100.2.102
```

Last step is to start the integrationtests with `integrationtests.sh`.  
One note for the integrationtests, I had to modify test_00_sync to first refresh the settings repo, then the template one.
```python3
    def test_00_sync(self):
        r = requests.put(
            f"{URL}/api/v1.0/repository/settings", headers=AUTH_HEADER, json={"action": "refresh"}, verify=TLS_VERIFY
        )
        print("Settings refresh status: {}".format(r.status_code))
        self.assertEqual(r.status_code, 200, "Failed to refresh settings")
        r = requests.put(
            f"{URL}/api/v1.0/repository/templates", headers=AUTH_HEADER, json={"action": "refresh"}, verify=TLS_VERIFY
        )
        print("Template refresh status: {}".format(r.status_code))
        self.assertEqual(r.status_code, 200, "Failed to refresh templates")
```
